name: markdown-lint-check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    markdown-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '23'

            - name: Install dependencies
              run: npm install

            - name: Run markdownlint
              run: npm run ci
